# Generated by Django 2.2.2 on 2020-11-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_cities',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_constellations',
            field=models.TextField(default='[]'),
        ),
    ]
