# Generated by Django 2.2.2 on 2020-11-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='md5',
        ),
        migrations.AddField(
            model_name='images',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
