# Generated by Django 2.2.2 on 2020-11-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_auto_20201124_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
    ]
